class Api {

  mock(characterName) {
    const history = [
        {
          letter: "a",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "a",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "a",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "a",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "a",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "a",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "b",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "b",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "b",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "b",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "b",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "b",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "c",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "c",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "c",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "c",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "c",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "c",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "d",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "d",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "d",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "d",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "d",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "d",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "e",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "e",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "e",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "e",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "e",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "e",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "f",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "f",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "f",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "f",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "f",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "f",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "g",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "g",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "g",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "g",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "g",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "g",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "h",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "h",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "h",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "h",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "h",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "h",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "i",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "i",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "i",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "i",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "i",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "i",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "j",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "j",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "j",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "j",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "j",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "j",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "k",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "k",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "k",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "k",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "k",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "k",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "l",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "l",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "l",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "l",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "l",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "l",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "m",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "m",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "m",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "m",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "m",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "m",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "n",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "n",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "n",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "n",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "n",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "n",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "o",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "o",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "o",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "o",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "o",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "o",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "p",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "p",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "p",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "p",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "p",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "p",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "q",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "q",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "q",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "q",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "q",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "q",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "r",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "r",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "r",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "r",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "r",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "r",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "s",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "s",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "s",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "s",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "s",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "s",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "t",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "t",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "t",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "t",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "t",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "t",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "u",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "u",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "u",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "u",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "u",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "u",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "v",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "v",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "v",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "v",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "v",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "v",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "w",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "w",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "w",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "w",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "w",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "w",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "x",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "x",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "x",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "x",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "x",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "x",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "y",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "y",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "y",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "y",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "y",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "y",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        {
          letter: "z",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/carlos.png",
          characterName: "carlos",
        },
        {
          letter: "z",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/adan.png",
          characterName: "adan",
        },
        {
          letter: "z",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/roger.png",
          characterName: "roger",
        },
        {
          letter: "z",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/bia.png",
          characterName: "bia",
        },
        {
          letter: "z",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/luiza.png",
          characterName: "luiza",
        },
        {
          letter: "z",
          textTop: "frase de teste",
          textBottom: "frase de teste",
          image: "file:///home/lucas/phooto/estudos/samples/basic/pages/julia.png",
          characterName: "julia",
        },
        
    ];
    
    return new Promise(resolve => {
      const response = history.filter(data => data.characterName === characterName);

      return resolve(response);
    })
  }

  async execute(data) {

    const { name, characterName, cover: coverColor, coverType, dedication } = data;

    
    let history = await this.mock(characterName);
    
    
    history.map(data => {
      if (data.letter === name.substr(0, 1).toLowerCase()) {
        data["textTop"] = `${name} ${data.textTop}`
      }
    })
    
    let dataResponse = {
      history,
      cover: `file:///home/lucas/phooto/estudos/samples/basic/pages/${coverColor}.jpg`,
      // pageName: "file:///home/lucas/phooto/estudos/samples/basic/pages/pageName.png",
      backgroundDedication: "file:///home/lucas/phooto/estudos/samples/basic/pages/dedication.jpg",
      dedication,
      name,
      coverType
    }

    return dataResponse
       
  }


  
}